/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2b322d",
        "on-error": "#ffffff",
        "primary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#410005",
        "secondary-fixed-dim": "#d2bbff",
        "surface-container-highest": "#dde4dd",
        "on-secondary": "#ffffff",
        "surface-tint": "#006c49",
        "tertiary-fixed": "#ffdad7",
        "surface-container-low": "#eef6ee",
        "surface-dim": "#d4dcd5",
        "background": "#f4fbf4",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3c4a42",
        "on-surface": "#161d19",
        "surface-container-high": "#e3eae3",
        "secondary-container": "#8a4cfc",
        "outline-variant": "#bbcabf",
        "surface": "#f4fbf4",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#711419",
        "on-primary-fixed": "#002113",
        "primary": "#006c49",
        "secondary-fixed": "#eaddff",
        "on-secondary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#842225",
        "primary-container": "#10b981",
        "error": "#ba1a1a",
        "on-primary-container": "#00422b",
        "surface-container": "#e8f0e9",
        "tertiary": "#a43a3a",
        "outline": "#6c7a71",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f4fbf4",
        "error-container": "#ffdad6",
        "on-background": "#161d19",
        "tertiary-container": "#fc7c78",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#25005a",
        "on-primary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf3eb",
        "inverse-primary": "#4edea3",
        "surface-variant": "#dde4dd",
        "secondary": "#712ae2",
        "tertiary-fixed-dim": "#ffb3af"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "sidebar-width": "260px",
        "margin-desktop": "32px",
        "header-height": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "display-md": ["Inter"],
        "mono-data": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-md": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
